wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.3
    start_time: 1649246249
    t:
      1:
      - 1
      - 12
      - 45
      - 55
      2:
      - 1
      - 12
      - 45
      - 55
      3:
      - 2
      - 14
      - 16
      4: 3.10.3
      5: 0.12.12
      8:
      - 5
batch_size:
  desc: null
  value: 32
lr:
  desc: null
  value: 0.001
n_epochs:
  desc: null
  value: 1
n_timesteps:
  desc: null
  value: 2
n_timesteps_eval:
  desc: null
  value: 2
