wandb_version: 1

WANDB_API_KEY:
  desc: null
  value: 1
_wandb:
  desc: null
  value:
    cli_version: 0.12.12
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.3
    start_time: 1649255511
    t:
      1:
      - 12
      - 45
      - 55
      2:
      - 12
      - 45
      - 55
      3:
      - 2
      - 14
      - 16
      4: 3.10.3
      5: 0.12.12
      8:
      - 5
batch_size:
  desc: null
  value: 32
data:
  desc: null
  value: ./data
dec_hidden:
  desc: null
  value:
  - '20'
  - '46'
  - '72'
default_config:
  desc: null
  value: ./configs/default_config.yaml
enc_hidden:
  desc: null
  value:
  - '52'
  - '20'
id:
  desc: null
  value: shade
latent_dist_min_std:
  desc: null
  value: 0.01
lr:
  desc: null
  value: 0.001
model:
  desc: null
  value: SimpleTDVAE
n_atoms:
  desc: null
  value: 12
n_data:
  desc: null
  value: 133770
n_dec_layers:
  desc: null
  value: 2
n_embed:
  desc: null
  value: 20
n_enc_layers:
  desc: null
  value: 2
n_epochs:
  desc: null
  value: 1
n_features:
  desc: null
  value: 84
n_input:
  desc: null
  value: null
n_target:
  desc: null
  value: null
n_target_features:
  desc: null
  value: 72
n_timesteps:
  desc: null
  value: 2
n_timesteps_eval:
  desc: null
  value: 2
n_transfer_layers:
  desc: null
  value: 2
prediction_std:
  desc: null
  value: 1.0
project:
  desc: null
  value: test
results:
  desc: null
  value: ./results/test
root:
  desc: null
  value: /home/amawi/projects/mol-td
seed:
  desc: null
  value: 1
uracil_xyz:
  desc: null
  value: ./data/uracil.xyz
use_wandb:
  desc: null
  value: true
user:
  desc: null
  value: xmax1
wandb_status:
  desc: null
  value: online
