wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.12
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.3
    start_time: 1649235007
    t:
      1:
      - 12
      - 45
      - 55
      2:
      - 12
      - 45
      - 55
      3:
      - 2
      - 14
      4: 3.10.3
      5: 0.12.12
      8:
      - 1
      - 5
